<?php
declare(strict_types=1);

namespace CB\CRM\Admin;

use CB\CRM\Content\ContactIdentity;
use CB\CRM\Content\Entity;
use CB\CRM\Content\Meta;
use CB\CRM\Content\PostTypes;
use CB\CRM\Content\RecordStatus;
use CB\CRM\PanelRegistry;
use CB\CRM\Repository\Activity;
use CB\CRM\Repository\Addresses;
use CB\CRM\Repository\ContactMethods;
use CB\CRM\Repository\Names;
use CB\CRM\Repository\Notes;
use CB\CRM\Repository\Organizations;
defined( 'ABSPATH' ) || exit;

final class Panels {
	public static function init(): void { add_action( 'cb_crm_register_panels', [ __CLASS__, 'register' ] ); }
	public static function register(): void {
		PanelRegistry::register( [ 'id' => 'details', 'label' => __( 'CRM Details', 'core-blueprint-crm' ), 'post_types' => [ Entity::CONTACT, Entity::ORGANIZATION ], 'render' => [ __CLASS__, 'details' ], 'context' => 'normal', 'priority' => 'high' ] );
		PanelRegistry::register( [ 'id' => 'contact-methods', 'label' => __( 'Contact Methods', 'core-blueprint-crm' ), 'post_types' => [ Entity::CONTACT, Entity::ORGANIZATION ], 'render' => [ __CLASS__, 'contact_methods' ] ] );
		PanelRegistry::register( [ 'id' => 'addresses', 'label' => __( 'Addresses', 'core-blueprint-crm' ), 'post_types' => [ Entity::CONTACT, Entity::ORGANIZATION ], 'render' => [ __CLASS__, 'addresses' ] ] );
		PanelRegistry::register( [ 'id' => 'names', 'label' => __( 'Names & Aliases', 'core-blueprint-crm' ), 'post_types' => [ Entity::CONTACT, Entity::ORGANIZATION ], 'render' => [ __CLASS__, 'names' ] ] );
		PanelRegistry::register( [ 'id' => 'organizations', 'label' => __( 'Organizations', 'core-blueprint-crm' ), 'post_types' => [ Entity::CONTACT ], 'render' => [ __CLASS__, 'organizations' ] ] );
		PanelRegistry::register( [ 'id' => 'notes-activity', 'label' => __( 'Notes & Activity', 'core-blueprint-crm' ), 'post_types' => [ Entity::CONTACT, Entity::ORGANIZATION ], 'render' => [ __CLASS__, 'notes_activity' ] ] );
	}

	public static function details( string $owner_type, int $post_id ): void {
		wp_nonce_field( 'cb_crm_save_record', 'cb_crm_nonce' );
		$status = RecordStatus::normalize( (string) get_post_meta( $post_id, Meta::STATUS, true ) );
		echo '<table class="form-table" role="presentation"><tbody><tr><th><label for="cb-crm-status">' . esc_html__( 'Status', 'core-blueprint-crm' ) . '</label></th><td><select id="cb-crm-status" name="cb_crm_details[status]">';
		foreach ( RecordStatus::labels() as $value => $label ) { echo '<option value="' . esc_attr( $value ) . '" ' . selected( $status, $value, false ) . '>' . esc_html( $label ) . '</option>'; }
		echo '</select></td></tr>';
		if ( Entity::CONTACT === $owner_type ) {
			$linked = ContactIdentity::linked_user_id( $post_id ); $linked_user = $linked > 0 ? get_userdata( $linked ) : false; if ( ! $linked_user instanceof \WP_User ) { $linked = 0; }
			$email_mode = sanitize_key( (string) get_post_meta( $post_id, Meta::EMAIL_MODE, true ) ); if ( ! in_array( $email_mode, [ ContactIdentity::EMAIL_CRM, ContactIdentity::EMAIL_WP ], true ) || ( ContactIdentity::EMAIL_WP === $email_mode && 0 === $linked ) ) { $email_mode = ContactIdentity::EMAIL_CRM; }
			echo '<tr><th><label for="cb-crm-first-name">' . esc_html__( 'First name', 'core-blueprint-crm' ) . '</label></th><td><input type="text" class="regular-text" id="cb-crm-first-name" name="cb_crm_details[first_name]" value="' . esc_attr( (string) get_post_meta( $post_id, Meta::FIRST_NAME, true ) ) . '"></td></tr>';
			echo '<tr><th><label for="cb-crm-last-name">' . esc_html__( 'Last name', 'core-blueprint-crm' ) . '</label></th><td><input type="text" class="regular-text" id="cb-crm-last-name" name="cb_crm_details[last_name]" value="' . esc_attr( (string) get_post_meta( $post_id, Meta::LAST_NAME, true ) ) . '"></td></tr>';
			echo '<tr><th><label for="cb-crm-job-title">' . esc_html__( 'Job title', 'core-blueprint-crm' ) . '</label></th><td><input type="text" class="regular-text" id="cb-crm-job-title" name="cb_crm_details[job_title]" value="' . esc_attr( (string) get_post_meta( $post_id, Meta::JOB_TITLE, true ) ) . '"></td></tr>';
			echo '<tr><th><label>' . esc_html__( 'WordPress account', 'core-blueprint-crm' ) . '</label></th><td><div class="cb-crm-user-picker" data-cb-crm-user-picker><input type="hidden" name="cb_crm_details[wp_user_id]" value="' . esc_attr( (string) $linked ) . '" data-cb-crm-user-id><input type="search" class="regular-text" autocomplete="off" placeholder="' . esc_attr__( 'Search by name or email…', 'core-blueprint-crm' ) . '" data-cb-crm-user-search><div class="cb-crm-user-results" role="listbox" hidden data-cb-crm-user-results></div></div></td></tr>';
			echo '<tr><th><label for="cb-crm-email-mode">' . esc_html__( 'Preferred email source', 'core-blueprint-crm' ) . '</label></th><td><select id="cb-crm-email-mode" name="cb_crm_details[email_mode]"><option value="crm" ' . selected( $email_mode, ContactIdentity::EMAIL_CRM, false ) . '>' . esc_html__( 'CRM contact methods', 'core-blueprint-crm' ) . '</option><option value="wp_user" ' . selected( $email_mode, ContactIdentity::EMAIL_WP, false ) . ' ' . disabled( 0 === $linked, true, false ) . '>' . esc_html__( 'Linked WordPress account', 'core-blueprint-crm' ) . '</option></select></td></tr>';
		} elseif ( Entity::ORGANIZATION === $owner_type ) {
			echo '<tr><th><label for="cb-crm-legal-name">' . esc_html__( 'Legal name', 'core-blueprint-crm' ) . '</label></th><td><input type="text" class="regular-text" id="cb-crm-legal-name" name="cb_crm_details[legal_name]" value="' . esc_attr( (string) get_post_meta( $post_id, Meta::LEGAL_NAME, true ) ) . '"></td></tr>';
		}
		echo '</tbody></table>';
	}

	public static function contact_methods( string $owner_type, int $post_id ): void { $rows = ContactMethods::for_owner( $owner_type, $post_id ); echo '<input type="hidden" name="cb_crm_contact_methods_present" value="1">'; self::table_start( 'contact-methods', count( $rows ), [ __( 'Type', 'core-blueprint-crm' ), __( 'Label', 'core-blueprint-crm' ), __( 'Value', 'core-blueprint-crm' ), __( 'Primary', 'core-blueprint-crm' ), __( 'Actions', 'core-blueprint-crm' ) ] ); foreach ( $rows as $i => $row ) { self::contact_method_row( $i, $row ); } self::table_template( static fn() => self::contact_method_row( '__INDEX__', [] ), __( 'Add contact method', 'core-blueprint-crm' ) ); }
	public static function addresses( string $owner_type, int $post_id ): void { $rows = Addresses::for_owner( $owner_type, $post_id ); echo '<input type="hidden" name="cb_crm_addresses_present" value="1"><div class="cb-crm-repeater" data-cb-crm-repeater data-next-index="' . esc_attr( (string) count( $rows ) ) . '"><div data-cb-crm-rows>'; foreach ( $rows as $i => $row ) { self::address_row( $i, $row ); } echo '</div><template>'; self::address_row( '__INDEX__', [] ); echo '</template><p><button type="button" class="button" data-cb-crm-add-row>' . esc_html__( 'Add address', 'core-blueprint-crm' ) . '</button></p></div>'; }
	public static function names( string $owner_type, int $post_id ): void { $rows = Names::for_owner( $owner_type, $post_id ); echo '<input type="hidden" name="cb_crm_names_present" value="1">'; self::table_start( 'names', count( $rows ), [ __( 'Name', 'core-blueprint-crm' ), __( 'Type', 'core-blueprint-crm' ), __( 'From', 'core-blueprint-crm' ), __( 'Until', 'core-blueprint-crm' ), __( 'Actions', 'core-blueprint-crm' ) ] ); foreach ( $rows as $i => $row ) { self::name_row( $i, $row ); } self::table_template( static fn() => self::name_row( '__INDEX__', [] ), __( 'Add name or alias', 'core-blueprint-crm' ) ); }
	public static function organizations( string $owner_type, int $post_id ): void { unset( $owner_type ); $rows = Organizations::for_contact( $post_id ); $options = get_posts( [ 'post_type' => PostTypes::ORGANIZATION, 'post_status' => [ 'publish', 'draft', 'private' ], 'numberposts' => -1, 'orderby' => 'title', 'order' => 'ASC' ] ); echo '<input type="hidden" name="cb_crm_organizations_present" value="1">'; self::table_start( 'organizations', count( $rows ), [ __( 'Organization', 'core-blueprint-crm' ), __( 'Role', 'core-blueprint-crm' ), __( 'From', 'core-blueprint-crm' ), __( 'Until', 'core-blueprint-crm' ), __( 'Primary', 'core-blueprint-crm' ), __( 'Actions', 'core-blueprint-crm' ) ] ); foreach ( $rows as $i => $row ) { self::organization_row( $i, $row, $options ); } self::table_template( static fn() => self::organization_row( '__INDEX__', [], $options ), __( 'Add organization', 'core-blueprint-crm' ) ); }
	public static function notes_activity( string $owner_type, int $post_id ): void { $notes = Notes::for_owner( $owner_type, $post_id, 20 ); $activity = Activity::for_owner( $owner_type, $post_id, 30 ); echo '<p><label for="cb-crm-new-note"><strong>' . esc_html__( 'Add note', 'core-blueprint-crm' ) . '</strong></label></p><textarea class="widefat" rows="3" id="cb-crm-new-note" name="cb_crm_new_note"></textarea><h3>' . esc_html__( 'Recent notes', 'core-blueprint-crm' ) . '</h3>'; if ( ! $notes ) { echo '<p class="description">' . esc_html__( 'No notes yet.', 'core-blueprint-crm' ) . '</p>'; } foreach ( $notes as $note ) { echo '<p><strong>' . esc_html( (string) $note['created_at'] ) . '</strong><br>' . nl2br( esc_html( (string) $note['body'] ) ) . '</p>'; } echo '<h3>' . esc_html__( 'Activity', 'core-blueprint-crm' ) . '</h3>'; if ( ! $activity ) { echo '<p class="description">' . esc_html__( 'No activity yet.', 'core-blueprint-crm' ) . '</p>'; } foreach ( $activity as $event ) { echo '<p><strong>' . esc_html( (string) $event['summary'] ) . '</strong><br><small>' . esc_html( (string) $event['source'] ) . ' · ' . esc_html( (string) $event['created_at'] ) . '</small></p>'; } }

	private static function table_start( string $id, int $next, array $labels ): void { echo '<div class="cb-crm-repeater" data-cb-crm-repeater data-next-index="' . esc_attr( (string) $next ) . '"><table class="widefat striped"><thead><tr>'; foreach ( $labels as $label ) { echo '<th>' . esc_html( $label ) . '</th>'; } echo '</tr></thead><tbody data-cb-crm-rows id="cb-crm-' . esc_attr( $id ) . '-rows">'; }
	private static function table_template( callable $render, string $label ): void { echo '</tbody></table><template>'; $render(); echo '</template><p><button type="button" class="button" data-cb-crm-add-row>' . esc_html( $label ) . '</button></p></div>'; }
	private static function contact_method_row( int|string $i, array $row ): void { $p = 'cb_crm_contact_methods[' . $i . ']'; echo '<tr data-cb-crm-row><td><select name="' . esc_attr( $p . '[method_type]' ) . '">'; foreach ( ContactMethods::TYPES as $type ) { echo '<option value="' . esc_attr( $type ) . '" ' . selected( (string) ( $row['method_type'] ?? 'email' ), $type, false ) . '>' . esc_html( ucfirst( $type ) ) . '</option>'; } echo '</select></td><td><input type="text" name="' . esc_attr( $p . '[label]' ) . '" value="' . esc_attr( (string) ( $row['label'] ?? '' ) ) . '"></td><td><input type="text" class="regular-text" name="' . esc_attr( $p . '[value]' ) . '" value="' . esc_attr( (string) ( $row['value'] ?? '' ) ) . '"></td><td><input type="checkbox" name="' . esc_attr( $p . '[is_primary]' ) . '" value="1" ' . checked( ! empty( $row['is_primary'] ), true, false ) . '></td><td><button type="button" class="button-link-delete" data-cb-crm-remove-row>' . esc_html__( 'Remove', 'core-blueprint-crm' ) . '</button></td></tr>'; }
	private static function address_row( int|string $i, array $row ): void { $p = 'cb_crm_addresses[' . $i . ']'; echo '<div class="postbox" data-cb-crm-row><div class="inside"><p><label>' . esc_html__( 'Label', 'core-blueprint-crm' ) . ' <input type="text" name="' . esc_attr( $p . '[label]' ) . '" value="' . esc_attr( (string) ( $row['label'] ?? '' ) ) . '"></label></p>'; foreach ( [ 'address_line_1' => 'Address line 1', 'address_line_2' => 'Address line 2', 'postal_code' => 'Postal code', 'city' => 'City', 'region' => 'Region', 'country' => 'Country code' ] as $key => $label ) { echo '<p><label>' . esc_html__( $label, 'core-blueprint-crm' ) . ' <input type="text" name="' . esc_attr( $p . '[' . $key . ']' ) . '" value="' . esc_attr( (string) ( $row[ $key ] ?? '' ) ) . '"></label></p>'; } echo '<p><label><input type="checkbox" name="' . esc_attr( $p . '[is_primary]' ) . '" value="1" ' . checked( ! empty( $row['is_primary'] ), true, false ) . '> ' . esc_html__( 'Primary address', 'core-blueprint-crm' ) . '</label> <button type="button" class="button-link-delete" data-cb-crm-remove-row>' . esc_html__( 'Remove', 'core-blueprint-crm' ) . '</button></p></div></div>'; }
	private static function name_row( int|string $i, array $row ): void { $p = 'cb_crm_names[' . $i . ']'; echo '<tr data-cb-crm-row><td><input type="text" name="' . esc_attr( $p . '[name]' ) . '" value="' . esc_attr( (string) ( $row['name'] ?? '' ) ) . '"></td><td><select name="' . esc_attr( $p . '[name_type]' ) . '">'; foreach ( Names::TYPES as $type ) { echo '<option value="' . esc_attr( $type ) . '" ' . selected( (string) ( $row['name_type'] ?? 'alias' ), $type, false ) . '>' . esc_html( ucfirst( $type ) ) . '</option>'; } echo '</select></td><td><input type="date" name="' . esc_attr( $p . '[started_at]' ) . '" value="' . esc_attr( (string) ( $row['started_at'] ?? '' ) ) . '"></td><td><input type="date" name="' . esc_attr( $p . '[ended_at]' ) . '" value="' . esc_attr( (string) ( $row['ended_at'] ?? '' ) ) . '"></td><td><button type="button" class="button-link-delete" data-cb-crm-remove-row>' . esc_html__( 'Remove', 'core-blueprint-crm' ) . '</button></td></tr>'; }
	private static function organization_row( int|string $i, array $row, array $options ): void { $p = 'cb_crm_organizations[' . $i . ']'; echo '<tr data-cb-crm-row><td><select name="' . esc_attr( $p . '[organization_id]' ) . '"><option value="0">—</option>'; foreach ( $options as $org ) { echo '<option value="' . esc_attr( (string) $org->ID ) . '" ' . selected( (int) ( $row['organization_id'] ?? 0 ), $org->ID, false ) . '>' . esc_html( $org->post_title ) . '</option>'; } echo '</select></td><td><input type="text" name="' . esc_attr( $p . '[role_title]' ) . '" value="' . esc_attr( (string) ( $row['role_title'] ?? '' ) ) . '"></td><td><input type="date" name="' . esc_attr( $p . '[started_at]' ) . '" value="' . esc_attr( (string) ( $row['started_at'] ?? '' ) ) . '"></td><td><input type="date" name="' . esc_attr( $p . '[ended_at]' ) . '" value="' . esc_attr( (string) ( $row['ended_at'] ?? '' ) ) . '"></td><td><input type="checkbox" name="' . esc_attr( $p . '[is_primary]' ) . '" value="1" ' . checked( ! empty( $row['is_primary'] ), true, false ) . '></td><td><button type="button" class="button-link-delete" data-cb-crm-remove-row>' . esc_html__( 'Remove', 'core-blueprint-crm' ) . '</button></td></tr>'; }
}
