<?php
declare(strict_types=1);

namespace CB\CRM\Integration\Builders\Bricks;

use CB\CRM\Content\Entity;
defined( 'ABSPATH' ) || exit;

final class DynamicData {
	private const GROUP = 'Core Blueprint CRM';
	/** @var array<string,array{type:string,field:string}> */
	private const FIELDS = [
		'cb_crm_contact_id' => [ 'type' => Entity::CONTACT, 'field' => 'id' ], 'cb_crm_contact_display_name' => [ 'type' => Entity::CONTACT, 'field' => 'display_name' ], 'cb_crm_contact_first_name' => [ 'type' => Entity::CONTACT, 'field' => 'first_name' ], 'cb_crm_contact_last_name' => [ 'type' => Entity::CONTACT, 'field' => 'last_name' ], 'cb_crm_contact_job_title' => [ 'type' => Entity::CONTACT, 'field' => 'job_title' ], 'cb_crm_contact_email' => [ 'type' => Entity::CONTACT, 'field' => 'primary_email' ], 'cb_crm_contact_phone' => [ 'type' => Entity::CONTACT, 'field' => 'primary_phone' ], 'cb_crm_contact_linked_user_id' => [ 'type' => Entity::CONTACT, 'field' => 'linked_user_id' ], 'cb_crm_contact_primary_organization' => [ 'type' => Entity::CONTACT, 'field' => 'primary_organization' ], 'cb_crm_contact_organizations' => [ 'type' => Entity::CONTACT, 'field' => 'organizations' ], 'cb_crm_contact_service_agreements' => [ 'type' => Entity::CONTACT, 'field' => 'service_agreements' ], 'cb_crm_contact_tags' => [ 'type' => Entity::CONTACT, 'field' => 'tags' ], 'cb_crm_contact_status' => [ 'type' => Entity::CONTACT, 'field' => 'status' ],
		'cb_crm_organization_id' => [ 'type' => Entity::ORGANIZATION, 'field' => 'id' ], 'cb_crm_organization_name' => [ 'type' => Entity::ORGANIZATION, 'field' => 'name' ], 'cb_crm_organization_legal_name' => [ 'type' => Entity::ORGANIZATION, 'field' => 'legal_name' ], 'cb_crm_organization_contact_methods' => [ 'type' => Entity::ORGANIZATION, 'field' => 'contact_methods' ], 'cb_crm_organization_address' => [ 'type' => Entity::ORGANIZATION, 'field' => 'address' ], 'cb_crm_organization_service_agreements' => [ 'type' => Entity::ORGANIZATION, 'field' => 'service_agreements' ], 'cb_crm_organization_tags' => [ 'type' => Entity::ORGANIZATION, 'field' => 'tags' ], 'cb_crm_organization_status' => [ 'type' => Entity::ORGANIZATION, 'field' => 'status' ],
	];
	public static function init(): void { add_filter( 'bricks/dynamic_tags_list', [ self::class, 'register_tags' ] ); add_filter( 'bricks/dynamic_data/render_tag', [ self::class, 'render_tag' ], 20, 3 ); add_filter( 'bricks/dynamic_data/render_content', [ self::class, 'render_content' ], 20, 3 ); add_filter( 'bricks/frontend/render_data', [ self::class, 'render_content' ], 20, 2 ); }
	/** @param array<int,array<string,mixed>> $tags @return array<int,array<string,mixed>> */ public static function register_tags( array $tags ): array { foreach ( self::labels() as $name => $label ) { $tags[] = [ 'name' => '{' . $name . '}', 'label' => $label, 'group' => self::GROUP ]; } return $tags; }
	public static function render_tag( mixed $tag, mixed $post = null, string $context = 'text' ): mixed { unset( $post, $context ); if ( ! is_string( $tag ) ) { return $tag; } $name = trim( $tag, '{}' ); return isset( self::FIELDS[ $name ] ) ? self::value_for( $name ) : $tag; }
	public static function render_content( mixed $content, mixed $post = null, string $context = 'text' ): mixed { unset( $post, $context ); if ( ! is_string( $content ) || false === strpos( $content, '{cb_crm_' ) ) { return $content; } foreach ( self::FIELDS as $name => $definition ) { unset( $definition ); $content = str_replace( '{' . $name . '}', self::value_for( $name ), $content ); } return $content; }
	private static function value_for( string $name ): string { $definition = self::FIELDS[ $name ]; $data = RecordContext::data( $definition['type'] ); if ( is_wp_error( $data ) ) { return ''; } return self::string_value( $definition['field'], $data[ $definition['field'] ] ?? null ); }
	private static function string_value( string $field, mixed $value ): string {
		if ( 'primary_organization' === $field && is_array( $value ) ) { return sanitize_text_field( (string) ( $value['name'] ?? '' ) ); }
		if ( 'address' === $field && is_array( $value ) ) { $parts = []; foreach ( [ 'address_line_1', 'address_line_2', 'postal_code', 'city', 'region', 'country' ] as $key ) { $part = sanitize_text_field( (string) ( $value[ $key ] ?? '' ) ); if ( '' !== $part ) { $parts[] = $part; } } return implode( ', ', $parts ); }
		if ( 'contact_methods' === $field && is_array( $value ) ) { $items = []; foreach ( $value as $row ) { if ( is_array( $row ) && is_scalar( $row['value'] ?? null ) ) { $item = sanitize_text_field( (string) $row['value'] ); if ( '' !== $item ) { $items[] = $item; } } } return implode( ', ', array_values( array_unique( $items ) ) ); }
		if ( 'service_agreements' === $field && is_array( $value ) ) { $items = []; foreach ( $value as $row ) { if ( is_array( $row ) && is_scalar( $row['service_name'] ?? null ) ) { $item = sanitize_text_field( (string) $row['service_name'] ); if ( '' !== $item ) { $items[] = $item; } } } return implode( ', ', array_values( array_unique( $items ) ) ); }
		if ( in_array( $field, [ 'organizations', 'tags' ], true ) && is_array( $value ) ) { $items = []; foreach ( $value as $row ) { if ( is_array( $row ) && is_scalar( $row['name'] ?? null ) ) { $item = sanitize_text_field( (string) $row['name'] ); if ( '' !== $item ) { $items[] = $item; } } } return implode( ', ', array_values( array_unique( $items ) ) ); }
		if ( is_bool( $value ) ) { return $value ? '1' : ''; } return is_scalar( $value ) ? (string) $value : '';
	}
	/** @return array<string,string> */
	private static function labels(): array { $contact = __( 'Contact', 'core-blueprint-crm' ); $organization = __( 'Organization', 'core-blueprint-crm' ); return [ 'cb_crm_contact_id' => $contact . ' · ID', 'cb_crm_contact_display_name' => $contact . ' · ' . __( 'Display name', 'core-blueprint-crm' ), 'cb_crm_contact_first_name' => $contact . ' · ' . __( 'First name', 'core-blueprint-crm' ), 'cb_crm_contact_last_name' => $contact . ' · ' . __( 'Last name', 'core-blueprint-crm' ), 'cb_crm_contact_job_title' => $contact . ' · ' . __( 'Job title', 'core-blueprint-crm' ), 'cb_crm_contact_email' => $contact . ' · ' . __( 'Email', 'core-blueprint-crm' ), 'cb_crm_contact_phone' => $contact . ' · ' . __( 'Phone', 'core-blueprint-crm' ), 'cb_crm_contact_linked_user_id' => $contact . ' · ' . __( 'Linked WordPress account', 'core-blueprint-crm' ), 'cb_crm_contact_primary_organization' => $contact . ' · ' . __( 'Primary organization', 'core-blueprint-crm' ), 'cb_crm_contact_organizations' => $contact . ' · ' . __( 'Organizations', 'core-blueprint-crm' ), 'cb_crm_contact_service_agreements' => $contact . ' · ' . __( 'Service Agreements', 'core-blueprint-crm' ), 'cb_crm_contact_tags' => $contact . ' · ' . __( 'CRM Tags', 'core-blueprint-crm' ), 'cb_crm_contact_status' => $contact . ' · ' . __( 'Status', 'core-blueprint-crm' ), 'cb_crm_organization_id' => $organization . ' · ID', 'cb_crm_organization_name' => $organization . ' · ' . __( 'Organization name', 'core-blueprint-crm' ), 'cb_crm_organization_legal_name' => $organization . ' · ' . __( 'Legal name', 'core-blueprint-crm' ), 'cb_crm_organization_contact_methods' => $organization . ' · ' . __( 'Contact Methods', 'core-blueprint-crm' ), 'cb_crm_organization_address' => $organization . ' · ' . __( 'Primary address', 'core-blueprint-crm' ), 'cb_crm_organization_service_agreements' => $organization . ' · ' . __( 'Service Agreements', 'core-blueprint-crm' ), 'cb_crm_organization_tags' => $organization . ' · ' . __( 'CRM Tags', 'core-blueprint-crm' ), 'cb_crm_organization_status' => $organization . ' · ' . __( 'Status', 'core-blueprint-crm' ) ]; }
}
